name: Auto Format with autopep8

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install autopep8
        run: pip install autopep8

      - name: Run autopep8 and fix code
        run: |
          autopep8 --in-place --recursive --max-line-length 120 --aggressive --aggressive .

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "add min_rating field for draw offers and resign"
            git push
          fi
