name: autopep8

on:
  push:
    paths:
      - '.github/workflows/autopep8.yml'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/autopep8.yml'
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8
    - name: Analysing the code with autopep8
      run: |
        autopep8 --diff --max-line-length 120 --aggressive --aggressive --exit-code $(git ls-files '*.py')
