name: Docker Build

on:
  push:
    paths: 'Dockerfile'
  pull_request:
      paths: 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag botli:$(date +%s)
