name: Auto Format with autopep8

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install autopep8
        run: pip install autopep8

      - name: Run autopep8
        run: |
          autopep8 --in-place --recursive --max-line-length 120 .

      - name: Commit formatting changes before pull
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Temporary autopep8 formatting commit"
          fi

      - name: Pull latest changes with rebase
        run: git pull --rebase origin main

      - name: Commit final changes
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit --amend -m "Add tournament dedicated opening books"
          else
            git commit --amend --no-edit
          fi

      - name: Push changes
        run: git push origin main --force-with-lease
