name: Pylint

on:
  push:
    paths:
      - '.github/workflows/pylint.yml'
      - '.pylintrc'
      - 'requirements.txt'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/pylint.yml'
      - '.pylintrc'
      - 'requirements.txt'
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
