name: Pyright

on:
  push:
    paths:
      - '.github/workflows/pyright.yml'
      - 'pyproject.toml'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/pyright.yml'
      - 'pyproject.toml'
      - '**.py'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
    - name: Install BotLi
      run: |
        uv sync --locked --dev
    - name: Analysing the code with pyright
      run: |
        uv run pyright --pythonversion 3.11
