name: Sync Toroms BotLi

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout our repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Add NNUE remote
        run: |
          git remote add botli https://github.com/Torom/BotLi.git || echo "BotLi already added"
          git fetch botli main

      - name: Merge NNUE into our repo
        run: |
          git merge botli/main --allow-unrelated-histories -X ours --no-edit || true
          git merge botli/main -X ours --no-edit || true
          git commit -am "Sync BotLi updates (ours wins on conflicts)" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main
